name: CI
on: push

env:
  RELEASE_FILES: |
    linux/*.so
    windows/*.dll

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr avr-libc libelf-dev freeglut3 freeglut3-dev
      - name: Configure build
        run: cmake -Bbuild -H.
      - name: Build
        run: cmake --build ./build
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: build/*.so

  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
      - name: Configure build
        run: cmake -Bbuild -H.
      - name: Build
        run: cmake --build ./build
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: build/*.dll

  release:
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
    needs: [build_ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release latest
        if: ${{ github.ref == 'refs/heads/main' }}
        # eine/tip force-pushes to the specified tag
        uses: eine/tip@master
        with:
          files: ${{ env.RELEASE_FILES }}
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release tagged
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.RELEASE_FILES }}
